### ISSUE TITLE
 bug: multi-account error

### ISSUE THREAD

**Issue by steven4354** [steven4354/email.dev#40]
```
May 28 10:45:02 PM  Campiagn id:  51393abd-3c93-4aa8-b1b8-2c359363518f  /  Sending email to:  [redacted]
May 28 10:45:04 PM  Campiagn id:  51393abd-3c93-4aa8-b1b8-2c359363518f  /  Sending email to:  [redacted]
May 28 10:45:07 PM  Campiagn id:  51393abd-3c93-4aa8-b1b8-2c359363518f  /  Sending email to:  [redacted]
May 28 10:45:08 PM  An error occurred during campaign 51393abd-3c93-4aa8-b1b8-2c359363518f: Error: Invalid login: 535 Authentication Failed
May 28 10:45:08 PM      at SMTPConnection._formatError (/opt/render/project/src/packages/email-service/node_modules/nodemailer/lib/smtp-connection/index.js:790:19)
May 28 10:45:08 PM      at SMTPConnection._actionAUTHComplete (/opt/render/project/src/packages/email-service/node_modules/nodemailer/lib/smtp-connection/index.js:1548:34)
May 28 10:45:08 PM      at SMTPConnection.<anonymous> (/opt/render/project/src/packages/email-service/node_modules/nodemailer/lib/smtp-connection/index.js:546:26)
May 28 10:45:08 PM      at SMTPConnection._processResponse (/opt/render/project/src/packages/email-service/node_modules/nodemailer/lib/smtp-connection/index.js:953:20)
May 28 10:45:08 PM      at SMTPConnection._onData (/opt/render/project/src/packages/email-service/node_modules/nodemailer/lib/smtp-connection/index.js:755:14)
May 28 10:45:08 PM      at TLSSocket.SMTPConnection._onSocketData (/opt/render/project/src/packages/email-service/node_modules/nodemailer/lib/smtp-connection/index.js:193:44)
May 28 10:45:08 PM      at TLSSocket.emit (events.js:376:20)
May 28 10:45:08 PM      at TLSSocket.emit (domain.js:470:12)
May 28 10:45:08 PM      at addChunk (internal/streams/readable.js:309:12)
May 28 10:45:08 PM      at readableAddChunk (internal/streams/readable.js:284:9) {
May 28 10:45:08 PM    code: 'EAUTH',
May 28 10:45:08 PM    response: '535 Authentication Failed',
May 28 10:45:08 PM    responseCode: 535,
May 28 10:45:08 PM    command: 'AUTH PLAIN'
May 28 10:45:08 PM  }
May 28 10:45:08 PM  Finished sending emails for this Every 5 minutes
```

**Comment by steven4354** [comment]
couple of ideas:

A) 
- write a cron job that runs every hour to check that an email account is valid or invalid by sending an email to test@example.com
- if the email account is invalid, remove that email account from all campaigns
- if that campaign is active and has just that erronous account and is active, move it to paused
- update the email accounts ui to show working/valid email accounts at the top and invalid ones at the bottom
- on the selector for create/edit campaign only show valid email accounts

B) 

open to any other implementations as well
